#!/usr/bin/env python3
"""
Generate database/seed/init.sql from Sofia GTFS static feed.

Downloads the GTFS ZIP from https://gtfs.sofiatraffic.bg/api/v1/static,
extracts stops.txt, routes.txt, and shapes.txt, and generates SQL INSERT
statements for the STIP database.

Usage:
    python ml/scripts/generate_gtfs_seed.py
"""

import csv
import io
import os
import sys
import urllib.request
import zipfile
from pathlib import Path

GTFS_URL = "https://gtfs.sofiatraffic.bg/api/v1/static"

# Sofia bounding box (matches Coordinates.cs validation)
SOFIA_LAT_MIN, SOFIA_LAT_MAX = 42.5, 42.85
SOFIA_LON_MIN, SOFIA_LON_MAX = 23.1, 23.6

# GTFS route_type -> STIP transit type
ROUTE_TYPE_MAP = {
    "0": 0,   # Tram
    "1": 1,   # Metro
    "2": 3,   # Rail (treat as Bus)
    "3": 3,   # Bus
    "11": 11, # Trolleybus
}


def download_gtfs() -> bytes:
    print(f"Downloading GTFS feed from {GTFS_URL} ...")
    req = urllib.request.Request(GTFS_URL, headers={"User-Agent": "STIP-SeedGenerator/1.0"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        data = resp.read()
    print(f"  Downloaded {len(data):,} bytes")
    return data


def read_csv_from_zip(zf: zipfile.ZipFile, filename: str) -> list[dict]:
    with zf.open(filename) as f:
        text = io.TextIOWrapper(f, encoding="utf-8-sig")
        return list(csv.DictReader(text))


def in_sofia(lat: float, lon: float) -> bool:
    return SOFIA_LAT_MIN <= lat <= SOFIA_LAT_MAX and SOFIA_LON_MIN <= lon <= SOFIA_LON_MAX


def escape_sql(s: str) -> str:
    return s.replace("'", "''")


def generate_stops_sql(stops: list[dict]) -> str:
    lines = []
    count = 0
    for row in stops:
        loc_type = row.get("location_type", "0").strip()
        if loc_type != "0":
            continue
        try:
            lat = float(row["stop_lat"])
            lon = float(row["stop_lon"])
        except (ValueError, KeyError):
            continue
        if not in_sofia(lat, lon):
            continue
        stop_id = escape_sql(row["stop_id"])
        stop_name = escape_sql(row["stop_name"].strip())
        lines.append(f"    ('{stop_id}', '{stop_name}', ST_GeogFromText('POINT({lon} {lat})'))")
        count += 1

    header = f"-- STOPS ({count} stops from GTFS Sofia feed)\n"
    header += "INSERT INTO stops (stop_id, stop_name, location) VALUES\n"
    return header + ",\n".join(lines) + "\nON CONFLICT (stop_id) DO NOTHING;"


def generate_routes_sql(routes: list[dict]) -> str:
    lines = []
    count = 0
    seen = set()
    for row in routes:
        route_id = row["route_id"].strip()
        if route_id in seen:
            continue
        seen.add(route_id)
        raw_type = row.get("route_type", "3").strip()
        route_type = ROUTE_TYPE_MAP.get(raw_type, 3)
        short_name = escape_sql(row.get("route_short_name", "").strip())
        long_name = escape_sql(row.get("route_long_name", "").strip())
        if not short_name and not long_name:
            continue
        lines.append(f"    ('{escape_sql(route_id)}', '{short_name}', '{long_name}', {route_type})")
        count += 1

    header = f"-- ROUTES ({count} routes from GTFS Sofia feed)\n"
    header += "INSERT INTO routes (route_id, short_name, long_name, route_type) VALUES\n"
    return header + ",\n".join(lines) + "\nON CONFLICT (route_id) DO NOTHING;"


def generate_shapes_sql(shapes: list[dict]) -> str:
    # Group by shape_id, order by sequence
    from collections import defaultdict
    grouped: dict[str, list[tuple[int, float, float]]] = defaultdict(list)
    for row in shapes:
        sid = row["shape_id"].strip()
        seq = int(row["shape_pt_sequence"])
        lat = float(row["shape_pt_lat"])
        lon = float(row["shape_pt_lon"])
        grouped[sid].append((seq, lat, lon))

    # Sort each shape by sequence
    for sid in grouped:
        grouped[sid].sort(key=lambda x: x[0])

    lines = []
    count = 0
    for sid in sorted(grouped.keys()):
        pts = grouped[sid]
        for seq, (orig_seq, lat, lon) in enumerate(pts, 1):
            lines.append(f"    ('{escape_sql(sid)}', {seq}, {lat}, {lon})")
            count += 1

    header = f"-- SHAPES ({len(grouped)} shapes, {count} points from GTFS Sofia feed)\n"
    header += "INSERT INTO shapes (route_id, sequence, lat, lon) VALUES\n"
    return header + ",\n".join(lines) + "\nON CONFLICT (route_id, sequence) DO NOTHING;"


def generate_sql(stops: list[dict], routes: list[dict], shapes: list[dict]) -> str:
    parts = [
        "-- ============================================================",
        "-- Generated from Sofia GTFS static feed",
        "-- Source: https://gtfs.sofiatraffic.bg/api/v1/static",
        f"-- Generated by ml/scripts/generate_gtfs_seed.py",
        "-- All INSERTs use ON CONFLICT DO NOTHING for idempotency.",
        "-- ============================================================",
        "",
        "-- ============================================================",
        "-- ROUTES",
        "-- ============================================================",
        generate_routes_sql(routes),
        "",
        "-- ============================================================",
        "-- STOPS",
        "-- ============================================================",
        generate_stops_sql(stops),
        "",
        "-- ============================================================",
        "-- SHAPES (route polylines)",
        "-- ============================================================",
        generate_shapes_sql(shapes),
        "",
    ]
    return "\n".join(parts) + "\n"


def main():
    gtfs_data = download_gtfs()

    buf = io.BytesIO(gtfs_data)
    with zipfile.ZipFile(buf) as zf:
        stops = read_csv_from_zip(zf, "stops.txt")
        routes = read_csv_from_zip(zf, "routes.txt")
        shapes = read_csv_from_zip(zf, "shapes.txt")

    print(f"  Stops: {len(stops)} total")
    print(f"  Routes: {len(routes)} total")
    print(f"  Shapes: {len(shapes)} points total")

    sql = generate_sql(stops, routes, shapes)

    out_path = Path(__file__).resolve().parent.parent / "database" / "seed" / "init.sql"
    out_path.write_text(sql, encoding="utf-8")
    print(f"\nWrote {out_path} ({len(sql):,} bytes)")

    # Print summary
    stop_count = sql.count("ON CONFLICT (stop_id)")
    route_count = sql.count("ON CONFLICT (route_id)")
    shape_lines = sql.count("ST_GeogFromText") if "ST_GeogFromText" in sql else 0
    print(f"\nSummary:")
    print(f"  Routes: ~{route_count} INSERT blocks")
    print(f"  Stops:  look for ST_GeogFromText entries")
    print(f"  Shapes: look for shape INSERT blocks")


if __name__ == "__main__":
    main()
