CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428101743_InitialCreate') THEN
    CREATE EXTENSION IF NOT EXISTS postgis;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428101743_InitialCreate') THEN
    CREATE TABLE delay_logs (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        vehicle_id text,
        stop_id text,
        trip_id text,
        route_id text,
        scheduled_arrival timestamp with time zone NOT NULL,
        actual_arrival timestamp with time zone NOT NULL,
        delay_seconds integer NOT NULL,
        recorded_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_delay_logs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428101743_InitialCreate') THEN
    CREATE TABLE reliability_scores (
        route_id text NOT NULL,
        score_date timestamp with time zone NOT NULL,
        on_time_pct double precision NOT NULL,
        avg_delay_seconds double precision NOT NULL,
        reliability_score double precision NOT NULL,
        peak_score double precision NOT NULL,
        sample_count integer NOT NULL,
        CONSTRAINT "PK_reliability_scores" PRIMARY KEY (route_id, score_date)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428101743_InitialCreate') THEN
    CREATE TABLE routes (
        route_id text NOT NULL,
        short_name text NOT NULL,
        long_name text,
        route_type integer NOT NULL,
        CONSTRAINT "PK_routes" PRIMARY KEY (route_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428101743_InitialCreate') THEN
    CREATE TABLE stops (
        stop_id text NOT NULL,
        stop_name text NOT NULL,
        location geography(POINT, 4326),
        CONSTRAINT "PK_stops" PRIMARY KEY (stop_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428101743_InitialCreate') THEN
    CREATE TABLE vehicles (
        vehicle_id text NOT NULL,
        route_id text,
        trip_id text,
        bearing real NOT NULL,
        speed real NOT NULL,
        recorded_at timestamp with time zone NOT NULL,
        location geography(POINT, 4326),
        CONSTRAINT "PK_vehicles" PRIMARY KEY (vehicle_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428101743_InitialCreate') THEN
    CREATE TABLE trips (
        trip_id text NOT NULL,
        route_id text NOT NULL,
        service_id text NOT NULL,
        direction_id integer NOT NULL,
        CONSTRAINT "PK_trips" PRIMARY KEY (trip_id),
        CONSTRAINT "FK_trips_routes_route_id" FOREIGN KEY (route_id) REFERENCES routes (route_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428101743_InitialCreate') THEN
    CREATE TABLE stop_times (
        trip_id text NOT NULL,
        stop_sequence integer NOT NULL,
        stop_id text NOT NULL,
        arrival_time interval NOT NULL,
        CONSTRAINT "PK_stop_times" PRIMARY KEY (trip_id, stop_sequence),
        CONSTRAINT "FK_stop_times_stops_stop_id" FOREIGN KEY (stop_id) REFERENCES stops (stop_id) ON DELETE CASCADE,
        CONSTRAINT "FK_stop_times_trips_trip_id" FOREIGN KEY (trip_id) REFERENCES trips (trip_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428101743_InitialCreate') THEN
    CREATE INDEX "IX_delay_logs_route_id_recorded_at" ON delay_logs (route_id, recorded_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428101743_InitialCreate') THEN
    CREATE INDEX "IX_delay_logs_stop_id_recorded_at" ON delay_logs (stop_id, recorded_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428101743_InitialCreate') THEN
    CREATE INDEX "IX_stop_times_stop_id" ON stop_times (stop_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428101743_InitialCreate') THEN
    CREATE INDEX "IX_trips_route_id" ON trips (route_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428101743_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260428101743_InitialCreate', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428120126_AddPerformanceIndicesAndSeedData') THEN
    DROP INDEX "IX_stop_times_stop_id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428120126_AddPerformanceIndicesAndSeedData') THEN
    DROP INDEX "IX_delay_logs_route_id_recorded_at";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428120126_AddPerformanceIndicesAndSeedData') THEN
    DROP INDEX "IX_delay_logs_stop_id_recorded_at";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428120126_AddPerformanceIndicesAndSeedData') THEN
    ALTER TABLE delay_logs ALTER COLUMN delay_seconds DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428120126_AddPerformanceIndicesAndSeedData') THEN
    INSERT INTO routes (route_id, long_name, short_name, route_type)
    VALUES ('r-204', 'Gotse Delchev – Orlov Most', '204', 3);
    INSERT INTO routes (route_id, long_name, short_name, route_type)
    VALUES ('r-260', 'Druzhba – Central Station', '260', 3);
    INSERT INTO routes (route_id, long_name, short_name, route_type)
    VALUES ('r-285', 'Mladost 1 – Lyulin', '285', 3);
    INSERT INTO routes (route_id, long_name, short_name, route_type)
    VALUES ('r-72', 'Zaharna Fabrika – Poduene', '72', 3);
    INSERT INTO routes (route_id, long_name, short_name, route_type)
    VALUES ('r-94', 'Studentski Grad – Sofia University', '94', 3);
    INSERT INTO routes (route_id, long_name, short_name, route_type)
    VALUES ('r-m1', 'Slivnitsa – Business Park', 'M1', 1);
    INSERT INTO routes (route_id, long_name, short_name, route_type)
    VALUES ('r-m2', 'Obelya – Vitosha', 'M2', 1);
    INSERT INTO routes (route_id, long_name, short_name, route_type)
    VALUES ('r-m3', 'Hadzhi Dimitar – Krasno Selo', 'M3', 1);
    INSERT INTO routes (route_id, long_name, short_name, route_type)
    VALUES ('r-m4', 'Obelya – Sofia Airport', 'M4', 1);
    INSERT INTO routes (route_id, long_name, short_name, route_type)
    VALUES ('r-tram-1', 'Ivan Vazov – Nadezhda', '1', 0);
    INSERT INTO routes (route_id, long_name, short_name, route_type)
    VALUES ('r-tram-10', 'Vitosha – Zapaden Park', '10', 0);
    INSERT INTO routes (route_id, long_name, short_name, route_type)
    VALUES ('r-tram-7', 'Borovo – Lyulin', '7', 0);
    INSERT INTO routes (route_id, long_name, short_name, route_type)
    VALUES ('r-trol-1', 'Stochna Gara – Ivan Vazov', '1', 11);
    INSERT INTO routes (route_id, long_name, short_name, route_type)
    VALUES ('r-trol-2', 'Hadzhi Dimitar – Buxton', '2', 11);
    INSERT INTO routes (route_id, long_name, short_name, route_type)
    VALUES ('r-trol-5', 'Mladost 2 – NDK', '5', 11);
    INSERT INTO routes (route_id, long_name, short_name, route_type)
    VALUES ('r-trol-9', 'Iztok – Gotse Delchev', '9', 11);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428120126_AddPerformanceIndicesAndSeedData') THEN
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-001', GEOGRAPHY 'SRID=4326;POINT (23.3342 42.6897)', 'Orlov Most');
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-002', GEOGRAPHY 'SRID=4326;POINT (23.3451 42.6939)', 'Sofia University');
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-003', GEOGRAPHY 'SRID=4326;POINT (23.3186 42.6871)', 'NDK');
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-004', GEOGRAPHY 'SRID=4326;POINT (23.3219 42.6977)', 'Serdika');
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-005', GEOGRAPHY 'SRID=4326;POINT (23.3216 42.7104)', 'Central Station');
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-006', GEOGRAPHY 'SRID=4326;POINT (23.3782 42.6564)', 'Mladost 1');
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-007', GEOGRAPHY 'SRID=4326;POINT (23.314 42.663)', 'Vitosha');
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-008', GEOGRAPHY 'SRID=4326;POINT (23.26 42.746)', 'Obelya');
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-009', GEOGRAPHY 'SRID=4326;POINT (23.264 42.719)', 'Lyulin');
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-010', GEOGRAPHY 'SRID=4326;POINT (23.395 42.662)', 'Druzhba');
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-011', GEOGRAPHY 'SRID=4326;POINT (23.352 42.687)', 'Iztok');
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-012', GEOGRAPHY 'SRID=4326;POINT (23.323 42.678)', 'Lozenets');
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-013', GEOGRAPHY 'SRID=4326;POINT (23.346 42.706)', 'Poduene');
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-014', GEOGRAPHY 'SRID=4326;POINT (23.3 42.68)', 'Krasno Selo');
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-015', GEOGRAPHY 'SRID=4326;POINT (23.292 42.668)', 'Borovo');
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-016', GEOGRAPHY 'SRID=4326;POINT (23.345 42.653)', 'Studentski Grad');
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-017', GEOGRAPHY 'SRID=4326;POINT (23.288 42.665)', 'Gotse Delchev');
    INSERT INTO stops (stop_id, location, stop_name)
    VALUES ('s-018', GEOGRAPHY 'SRID=4326;POINT (23.295 42.72)', 'Zaharna Fabrika');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428120126_AddPerformanceIndicesAndSeedData') THEN
    CREATE INDEX idx_vehicles_recorded_at ON vehicles (recorded_at DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428120126_AddPerformanceIndicesAndSeedData') THEN
    CREATE INDEX idx_vehicles_route_id ON vehicles (route_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428120126_AddPerformanceIndicesAndSeedData') THEN
    CREATE INDEX idx_stops_name ON stops (stop_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428120126_AddPerformanceIndicesAndSeedData') THEN
    CREATE INDEX idx_stop_times_stop_arrival ON stop_times (stop_id, arrival_time);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428120126_AddPerformanceIndicesAndSeedData') THEN
    CREATE INDEX idx_delay_logs_recorded_at ON delay_logs (recorded_at DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428120126_AddPerformanceIndicesAndSeedData') THEN
    CREATE INDEX idx_delay_logs_route ON delay_logs (route_id, recorded_at DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428120126_AddPerformanceIndicesAndSeedData') THEN
    CREATE INDEX idx_delay_logs_stop ON delay_logs (stop_id, recorded_at DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428120126_AddPerformanceIndicesAndSeedData') THEN
    CREATE INDEX idx_delay_logs_vehicle ON delay_logs (vehicle_id, recorded_at DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428120126_AddPerformanceIndicesAndSeedData') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260428120126_AddPerformanceIndicesAndSeedData', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428150000_AddUsers') THEN
    CREATE TABLE users (
        id uuid NOT NULL,
        email text NOT NULL,
        password_hash text NOT NULL,
        full_name text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_users" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428150000_AddUsers') THEN
    CREATE UNIQUE INDEX idx_users_email ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428150000_AddUsers') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260428150000_AddUsers', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428194826_AddShapes') THEN
    CREATE TABLE shapes (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        route_id text NOT NULL,
        sequence integer NOT NULL,
        lat double precision NOT NULL,
        lon double precision NOT NULL,
        CONSTRAINT "PK_shapes" PRIMARY KEY (id),
        CONSTRAINT "FK_shapes_routes_route_id" FOREIGN KEY (route_id) REFERENCES routes (route_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428194826_AddShapes') THEN
    CREATE INDEX idx_shapes_route_sequence ON shapes (route_id, sequence);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428194826_AddShapes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260428194826_AddShapes', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507194746_AddUserFavorites') THEN
    DROP INDEX idx_vehicles_route_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507194746_AddUserFavorites') THEN
    DROP INDEX idx_shapes_route_sequence;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507194746_AddUserFavorites') THEN
    ALTER TABLE vehicles ALTER COLUMN recorded_at SET DEFAULT (now());
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507194746_AddUserFavorites') THEN
    ALTER TABLE vehicles ALTER COLUMN location SET NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507194746_AddUserFavorites') THEN
    ALTER TABLE stops ALTER COLUMN location SET NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507194746_AddUserFavorites') THEN
    ALTER TABLE stop_times ADD departure_time interval;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507194746_AddUserFavorites') THEN
    ALTER TABLE reliability_scores ALTER COLUMN sample_count SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507194746_AddUserFavorites') THEN
    ALTER TABLE delay_logs ALTER COLUMN recorded_at SET DEFAULT (now());
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507194746_AddUserFavorites') THEN
    UPDATE routes SET long_name = 'Sofia University – Mladost 1'
    WHERE route_id = 'r-tram-1';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507194746_AddUserFavorites') THEN
    CREATE INDEX idx_vehicles_location ON vehicles USING GIST (location);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507194746_AddUserFavorites') THEN
    CREATE INDEX idx_vehicles_route_id ON vehicles (route_id, recorded_at DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507194746_AddUserFavorites') THEN
    CREATE INDEX idx_vehicles_trip_id ON vehicles (trip_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507194746_AddUserFavorites') THEN
    CREATE INDEX idx_stops_location ON stops USING GIST (location);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507194746_AddUserFavorites') THEN
    CREATE INDEX idx_stop_times_trip_stop ON stop_times (trip_id, stop_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507194746_AddUserFavorites') THEN
    CREATE UNIQUE INDEX idx_shapes_route_sequence ON shapes (route_id, sequence);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507194746_AddUserFavorites') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260507194746_AddUserFavorites', '10.0.7');
    END IF;
END $EF$;
COMMIT;

