// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SofiaTransport.Infrastructure.Persistence;

#nullable disable

namespace SofiaTransport.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TransportDbContext))]
    [Migration("20260428101743_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SofiaTransport.Domain.Entities.DelayLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ActualArrival")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_arrival");

                    b.Property<int>("DelaySeconds")
                        .HasColumnType("integer")
                        .HasColumnName("delay_seconds");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RouteId")
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<DateTime>("ScheduledArrival")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_arrival");

                    b.Property<string>("StopId")
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<string>("VehicleId")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("RouteId", "RecordedAt");

                    b.HasIndex("StopId", "RecordedAt");

                    b.ToTable("delay_logs", (string)null);
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.ReliabilityScore", b =>
                {
                    b.Property<string>("RouteId")
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<DateTime>("ScoreDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("score_date");

                    b.Property<double>("AvgDelaySeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_delay_seconds");

                    b.Property<double>("OnTimePct")
                        .HasColumnType("double precision")
                        .HasColumnName("on_time_pct");

                    b.Property<double>("PeakScore")
                        .HasColumnType("double precision")
                        .HasColumnName("peak_score");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer")
                        .HasColumnName("sample_count");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("reliability_score");

                    b.HasKey("RouteId", "ScoreDate");

                    b.ToTable("reliability_scores", (string)null);
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.Route", b =>
                {
                    b.Property<string>("RouteId")
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<string>("LongName")
                        .HasColumnType("text")
                        .HasColumnName("long_name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("route_type");

                    b.HasKey("RouteId");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.Stop", b =>
                {
                    b.Property<string>("StopId")
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.Property<Point>("Geometry")
                        .HasColumnType("geography(POINT, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("StopName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_name");

                    b.HasKey("StopId");

                    b.ToTable("stops", (string)null);
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.StopTime", b =>
                {
                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<int>("StopSequence")
                        .HasColumnType("integer")
                        .HasColumnName("stop_sequence");

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("interval")
                        .HasColumnName("arrival_time");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.HasKey("TripId", "StopSequence");

                    b.HasIndex("StopId");

                    b.ToTable("stop_times", (string)null);
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.Trip", b =>
                {
                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<int>("DirectionId")
                        .HasColumnType("integer")
                        .HasColumnName("direction_id");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.HasKey("TripId");

                    b.HasIndex("RouteId");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.Vehicle", b =>
                {
                    b.Property<string>("VehicleId")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_id");

                    b.Property<float>("Bearing")
                        .HasColumnType("real")
                        .HasColumnName("bearing");

                    b.Property<Point>("Geometry")
                        .HasColumnType("geography(POINT, 4326)")
                        .HasColumnName("location");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RouteId")
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<float>("Speed")
                        .HasColumnType("real")
                        .HasColumnName("speed");

                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.HasKey("VehicleId");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.StopTime", b =>
                {
                    b.HasOne("SofiaTransport.Domain.Entities.Stop", "Stop")
                        .WithMany()
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SofiaTransport.Domain.Entities.Trip", "Trip")
                        .WithMany("StopTimes")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stop");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.Trip", b =>
                {
                    b.HasOne("SofiaTransport.Domain.Entities.Route", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.Route", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.Trip", b =>
                {
                    b.Navigation("StopTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
