// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SofiaTransport.Infrastructure.Persistence;

#nullable disable

namespace SofiaTransport.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TransportDbContext))]
    partial class TransportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SofiaTransport.Domain.Entities.DelayLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ActualArrival")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_arrival");

                    b.Property<int?>("DelaySeconds")
                        .HasColumnType("integer")
                        .HasColumnName("delay_seconds");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RouteId")
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<DateTime>("ScheduledArrival")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_arrival");

                    b.Property<string>("StopId")
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<string>("VehicleId")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_delay_logs_recorded_at");

                    b.HasIndex("RouteId", "RecordedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_delay_logs_route");

                    b.HasIndex("StopId", "RecordedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_delay_logs_stop");

                    b.HasIndex("VehicleId", "RecordedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_delay_logs_vehicle");

                    b.ToTable("delay_logs", (string)null);
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.ReliabilityScore", b =>
                {
                    b.Property<string>("RouteId")
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<DateTime>("ScoreDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("score_date");

                    b.Property<double>("AvgDelaySeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_delay_seconds");

                    b.Property<double>("OnTimePct")
                        .HasColumnType("double precision")
                        .HasColumnName("on_time_pct");

                    b.Property<double>("PeakScore")
                        .HasColumnType("double precision")
                        .HasColumnName("peak_score");

                    b.Property<int>("SampleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sample_count");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("reliability_score");

                    b.HasKey("RouteId", "ScoreDate");

                    b.ToTable("reliability_scores", (string)null);
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.Route", b =>
                {
                    b.Property<string>("RouteId")
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<string>("LongName")
                        .HasColumnType("text")
                        .HasColumnName("long_name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("route_type");

                    b.HasKey("RouteId");

                    b.ToTable("routes", (string)null);

                    b.HasData(
                        new
                        {
                            RouteId = "r-204",
                            LongName = "Gotse Delchev – Orlov Most",
                            ShortName = "204",
                            Type = 3
                        },
                        new
                        {
                            RouteId = "r-94",
                            LongName = "Studentski Grad – Sofia University",
                            ShortName = "94",
                            Type = 3
                        },
                        new
                        {
                            RouteId = "r-285",
                            LongName = "Mladost 1 – Lyulin",
                            ShortName = "285",
                            Type = 3
                        },
                        new
                        {
                            RouteId = "r-260",
                            LongName = "Druzhba – Central Station",
                            ShortName = "260",
                            Type = 3
                        },
                        new
                        {
                            RouteId = "r-72",
                            LongName = "Zaharna Fabrika – Poduene",
                            ShortName = "72",
                            Type = 3
                        },
                        new
                        {
                            RouteId = "r-tram-1",
                            LongName = "Sofia University – Mladost 1",
                            ShortName = "1",
                            Type = 0
                        },
                        new
                        {
                            RouteId = "r-tram-7",
                            LongName = "Borovo – Lyulin",
                            ShortName = "7",
                            Type = 0
                        },
                        new
                        {
                            RouteId = "r-tram-10",
                            LongName = "Vitosha – Zapaden Park",
                            ShortName = "10",
                            Type = 0
                        },
                        new
                        {
                            RouteId = "r-trol-1",
                            LongName = "Stochna Gara – Ivan Vazov",
                            ShortName = "1",
                            Type = 11
                        },
                        new
                        {
                            RouteId = "r-trol-2",
                            LongName = "Hadzhi Dimitar – Buxton",
                            ShortName = "2",
                            Type = 11
                        },
                        new
                        {
                            RouteId = "r-trol-5",
                            LongName = "Mladost 2 – NDK",
                            ShortName = "5",
                            Type = 11
                        },
                        new
                        {
                            RouteId = "r-trol-9",
                            LongName = "Iztok – Gotse Delchev",
                            ShortName = "9",
                            Type = 11
                        },
                        new
                        {
                            RouteId = "r-m1",
                            LongName = "Slivnitsa – Business Park",
                            ShortName = "M1",
                            Type = 1
                        },
                        new
                        {
                            RouteId = "r-m2",
                            LongName = "Obelya – Vitosha",
                            ShortName = "M2",
                            Type = 1
                        },
                        new
                        {
                            RouteId = "r-m3",
                            LongName = "Hadzhi Dimitar – Krasno Selo",
                            ShortName = "M3",
                            Type = 1
                        },
                        new
                        {
                            RouteId = "r-m4",
                            LongName = "Obelya – Sofia Airport",
                            ShortName = "M4",
                            Type = 1
                        });
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.Shape", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision")
                        .HasColumnName("lon");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("RouteId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("idx_shapes_route_sequence");

                    b.ToTable("shapes", (string)null);
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.Stop", b =>
                {
                    b.Property<string>("StopId")
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.Property<Point>("Geometry")
                        .IsRequired()
                        .HasColumnType("geography(POINT, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("StopName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_name");

                    b.HasKey("StopId");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("idx_stops_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.HasIndex("StopName")
                        .HasDatabaseName("idx_stops_name");

                    b.ToTable("stops", (string)null);

                    b.HasData(
                        new
                        {
                            StopId = "s-001",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.3342 42.6897)"),
                            StopName = "Orlov Most"
                        },
                        new
                        {
                            StopId = "s-002",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.3451 42.6939)"),
                            StopName = "Sofia University"
                        },
                        new
                        {
                            StopId = "s-003",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.3186 42.6871)"),
                            StopName = "NDK"
                        },
                        new
                        {
                            StopId = "s-004",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.3219 42.6977)"),
                            StopName = "Serdika"
                        },
                        new
                        {
                            StopId = "s-005",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.3216 42.7104)"),
                            StopName = "Central Station"
                        },
                        new
                        {
                            StopId = "s-006",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.3782 42.6564)"),
                            StopName = "Mladost 1"
                        },
                        new
                        {
                            StopId = "s-007",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.314 42.663)"),
                            StopName = "Vitosha"
                        },
                        new
                        {
                            StopId = "s-008",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.26 42.746)"),
                            StopName = "Obelya"
                        },
                        new
                        {
                            StopId = "s-009",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.264 42.719)"),
                            StopName = "Lyulin"
                        },
                        new
                        {
                            StopId = "s-010",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.395 42.662)"),
                            StopName = "Druzhba"
                        },
                        new
                        {
                            StopId = "s-011",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.352 42.687)"),
                            StopName = "Iztok"
                        },
                        new
                        {
                            StopId = "s-012",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.323 42.678)"),
                            StopName = "Lozenets"
                        },
                        new
                        {
                            StopId = "s-013",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.346 42.706)"),
                            StopName = "Poduene"
                        },
                        new
                        {
                            StopId = "s-014",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.3 42.68)"),
                            StopName = "Krasno Selo"
                        },
                        new
                        {
                            StopId = "s-015",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.292 42.668)"),
                            StopName = "Borovo"
                        },
                        new
                        {
                            StopId = "s-016",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.345 42.653)"),
                            StopName = "Studentski Grad"
                        },
                        new
                        {
                            StopId = "s-017",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.288 42.665)"),
                            StopName = "Gotse Delchev"
                        },
                        new
                        {
                            StopId = "s-018",
                            Geometry = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.295 42.72)"),
                            StopName = "Zaharna Fabrika"
                        });
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.StopTime", b =>
                {
                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<int>("StopSequence")
                        .HasColumnType("integer")
                        .HasColumnName("stop_sequence");

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("interval")
                        .HasColumnName("arrival_time");

                    b.Property<TimeSpan?>("DepartureTime")
                        .HasColumnType("interval")
                        .HasColumnName("departure_time");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.HasKey("TripId", "StopSequence");

                    b.HasIndex("StopId", "ArrivalTime")
                        .HasDatabaseName("idx_stop_times_stop_arrival");

                    b.HasIndex("TripId", "StopId")
                        .HasDatabaseName("idx_stop_times_trip_stop");

                    b.ToTable("stop_times", (string)null);
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.Trip", b =>
                {
                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<int>("DirectionId")
                        .HasColumnType("integer")
                        .HasColumnName("direction_id");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.HasKey("TripId");

                    b.HasIndex("RouteId");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.Vehicle", b =>
                {
                    b.Property<string>("VehicleId")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_id");

                    b.Property<float>("Bearing")
                        .HasColumnType("real")
                        .HasColumnName("bearing");

                    b.Property<Point>("Geometry")
                        .IsRequired()
                        .HasColumnType("geography(POINT, 4326)")
                        .HasColumnName("location");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RouteId")
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<float>("Speed")
                        .HasColumnType("real")
                        .HasColumnName("speed");

                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.HasKey("VehicleId");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("idx_vehicles_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.HasIndex("RecordedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_vehicles_recorded_at");

                    b.HasIndex("TripId")
                        .HasDatabaseName("idx_vehicles_trip_id");

                    b.HasIndex("RouteId", "RecordedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_vehicles_route_id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.Shape", b =>
                {
                    b.HasOne("SofiaTransport.Domain.Entities.Route", "Route")
                        .WithMany("Shapes")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.StopTime", b =>
                {
                    b.HasOne("SofiaTransport.Domain.Entities.Stop", "Stop")
                        .WithMany()
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SofiaTransport.Domain.Entities.Trip", "Trip")
                        .WithMany("StopTimes")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stop");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.Trip", b =>
                {
                    b.HasOne("SofiaTransport.Domain.Entities.Route", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.Route", b =>
                {
                    b.Navigation("Shapes");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("SofiaTransport.Domain.Entities.Trip", b =>
                {
                    b.Navigation("StopTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
