FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /backend
COPY backend/ .
RUN dotnet publish SofiaTransport.Worker/SofiaTransport.Worker.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app .
RUN useradd -m -u 1500 appuser && chown -R appuser:appuser /app
USER appuser
ENTRYPOINT ["dotnet", "SofiaTransport.Worker.dll"]
