FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /backend
COPY backend/ .
RUN dotnet publish SofiaTransport.Api/SofiaTransport.Api.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app .
RUN apt-get update && apt-get install -y --no-install-recommends curl libgssapi-krb5-2 && rm -rf /var/lib/apt/lists/*
RUN useradd -m -u 1500 appuser && chown -R appuser:appuser /app
USER appuser
EXPOSE 5000
ENTRYPOINT ["dotnet", "SofiaTransport.Api.dll"]
