using Xunit;
using SofiaTransport.Domain.Entities;

namespace SofiaTransport.Domain.Tests.Entities;

public class UserTests
{
    [Fact]
    public void Constructor_DefaultValues_AreSetCorrectly()
    {
        var user = new User();
        Assert.NotEqual(Guid.Empty, user.Id);
        Assert.Equal(string.Empty, user.Email);
        Assert.Equal(string.Empty, user.PasswordHash);
        Assert.Equal(string.Empty, user.FullName);
        Assert.True(user.CreatedAt <= DateTime.UtcNow);
    }

    [Fact]
    public void Properties_CanBeSetAndGet()
    {
        var id = Guid.NewGuid();
        var createdAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc);

        var user = new User
        {
            Id = id,
            Email = "test@example.com",
            PasswordHash = "$2a$12$hash",
            FullName = "Ivan Ivanov",
            CreatedAt = createdAt
        };

        Assert.Equal(id, user.Id);
        Assert.Equal("test@example.com", user.Email);
        Assert.Equal("$2a$12$hash", user.PasswordHash);
        Assert.Equal("Ivan Ivanov", user.FullName);
        Assert.Equal(createdAt, user.CreatedAt);
    }

    [Fact]
    public void Id_AutoGenerated_IsNotEmpty()
    {
        var user = new User();
        Assert.NotEqual(Guid.Empty, user.Id);
    }

    [Fact]
    public void CreatedAt_AutoSet_IsNearUtcNow()
    {
        var before = DateTime.UtcNow;
        var user = new User();
        var after = DateTime.UtcNow;

        Assert.True(user.CreatedAt >= before.AddSeconds(-1));
        Assert.True(user.CreatedAt <= after.AddSeconds(1));
    }
}
